---
- name: Playbook for OSPF routing 
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Task to create loopback adaptor
      ios_config:
        lines:
          - "ip address {{ lo0_add }} 255.255.255.255"
        parents: interface loopback 0
    
    - name: Task to Configure OSPF setting
      ios_config:
        lines:
          - "network {{ item.network }} {{ item.subnet }} area 0"
        parents: router ospf 1
      with_items: "{{ connected_network }}"

    - name: Task to save configuration
      ios_config:
        save_when: always
 
      
        