---
lo0_add: 4.4.4.4

connected_network:
  - network: 192.168.4.0
    subnet: 0.0.0.255
  - network: 14.14.14.0
    subnet: 0.0.0.3
  - network: 45.45.45.0
    subnet: 0.0.0.3
  - network: 4.4.4.4
    subnet: 0.0.0.0