---
- name: Banner Playbook for cisco devices
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Task to configure MOTD banner
      ios_banner:
        banner: motd
        text: |
          *****************************************************************************************
          *                                                                                       *
          *        Please log out immediately if you are not an authorized administrator.         *
          *                                                                                       *
          *****************************************************************************************
        state: present
  
    - name: additionanl changes
      ios_config:
        lines: 
          - no ip domain-lookup
          - line console 0
          - logging synchronous
          - exec-timeout 0 0
        save_when: modified